/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 27-May-2024 14:33:14 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Admin` CASCADE
;

DROP TABLE IF EXISTS `Business Client` CASCADE
;

DROP TABLE IF EXISTS `Business Contract` CASCADE
;

DROP TABLE IF EXISTS `Business Job` CASCADE
;

DROP TABLE IF EXISTS `Car` CASCADE
;

DROP TABLE IF EXISTS `Car Owner` CASCADE
;

DROP TABLE IF EXISTS `Driver` CASCADE
;

DROP TABLE IF EXISTS `Manager` CASCADE
;

DROP TABLE IF EXISTS `Office` CASCADE
;

DROP TABLE IF EXISTS `Private Client` CASCADE
;

DROP TABLE IF EXISTS `Private Job` CASCADE
;

/* Create Tables */

CREATE TABLE `Admin`
(
	`id` INT NOT NULL,
	`office_id` INT NULL,
	`name` VARCHAR(50) NULL,
	`age` INT NULL,
	`phone` INT NULL,
	CONSTRAINT `PK_Admin` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Business Client`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NULL,
	`gender` VARCHAR(1) NULL,
	`age` INT NULL,
	`phone` INT NULL,
	`address` VARCHAR(50) NULL,
	CONSTRAINT `PK_Business Client` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Business Contract`
(
	`id` INT NOT NULL,
	`office_id` INT NULL,
	`client_id` INT NULL,
	`number_of_jobs` INT NULL,
	`fee` INT NULL,
	`status` VARCHAR(50) NULL,
	CONSTRAINT `PK_Business Contract` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Business Job`
(
	`id` INT NOT NULL,
	`driver_id` INT NULL,
	`contract_id` INT NULL,
	`car_id` INT NULL,
	`pick_up_adr` VARCHAR(50) NULL,
	`drop_off_adr` VARCHAR(50) NULL,
	`status` VARCHAR(50) NULL,
	CONSTRAINT `PK_Business Job` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Car`
(
	`id` INT NOT NULL,
	`car_owner_id` INT NULL,
	`office_id` INT NULL,
	`manufacturer` VARCHAR(50) NULL,
	`model` VARCHAR(50) NULL,
	`reg_plate` VARCHAR(50) NULL,
	CONSTRAINT `PK_Car` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Car Owner`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NULL,
	`gender` VARCHAR(1) NULL,
	`age` INT NULL,
	`phone` INT NULL,
	CONSTRAINT `PK_Car Owner` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Driver`
(
	`id` INT NOT NULL,
	`office_id` INT NULL,
	`name` VARCHAR(50) NULL,
	`gender` VARCHAR(1) NULL,
	`age` INT NULL,
	`phone` INT NULL,
	CONSTRAINT `PK_Driver` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Manager`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NULL,
	`gender` VARCHAR(1) NULL,
	`age` INT NULL,
	`phone` INT NULL,
	CONSTRAINT `PK_Manager` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Office`
(
	`id` INT NOT NULL,
	`manager_id` INT NULL,
	`city` VARCHAR(50) NULL,
	`address` VARCHAR(50) NULL,
	`business_phone` INT NULL,
	CONSTRAINT `PK_Office` PRIMARY KEY (`id` ASC)
)
COMMENT = 'The Office is an American mockumentary sitcom television series based on the 2001–2003 BBC series of the same name created by (and starring) Ricky Gervais and Stephen Merchant. Adapted for American television by Greg Daniels, a veteran writer for Saturday Night Live, King of the Hill, and The Simpsons, the show depicts the everyday work lives of office employees at the Scranton, Pennsylvania, branch of the fictional Dunder Mifflin Paper Company, and aired on NBC from March 24, 2005, to May 16, 2013, with a total of nine seasons consisting of 201 episodes.[1] The show was co-produced by Daniels'' Deedle-Dee Productions and Reveille Productions (later Shine America), in association with Universal Television. The original executive producers were Daniels, Gervais, Merchant, Howard Klein and Ben Silverman, with numerous others being promoted in later seasons.'

;

CREATE TABLE `Private Client`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NULL,
	`gender` VARCHAR(1) NULL,
	`age` INT NULL,
	`phone` INT NULL,
	`contact_number` INT NULL,
	CONSTRAINT `PK_Private Client` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Private Job`
(
	`id` INT NOT NULL,
	`driver_id` INT NULL,
	`client_id` INT NULL,
	`car_id` INT NULL,
	`time` VARCHAR(50) NULL,
	`pick_up_adr` VARCHAR(50) NULL,
	`drop_off_adr` VARCHAR(50) NULL,
	`miles` INT NULL,
	`status` VARCHAR(50) NULL,
	CONSTRAINT `PK_Private Job` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Admin` 
 ADD INDEX `IXFK_Admin_Office` (`office_id` ASC)
;

ALTER TABLE `Business Contract` 
 ADD INDEX `IXFK_Business Contract_Business Client` (`client_id` ASC)
;

ALTER TABLE `Business Contract` 
 ADD INDEX `IXFK_Business Contract_Office` (`office_id` ASC)
;

ALTER TABLE `Business Job` 
 ADD INDEX `IXFK_Business Job_Business Contract` (`contract_id` ASC)
;

ALTER TABLE `Business Job` 
 ADD INDEX `IXFK_Business Job_Car` (`car_id` ASC)
;

ALTER TABLE `Business Job` 
 ADD INDEX `IXFK_Business Job_Driver` (`driver_id` ASC)
;

ALTER TABLE `Car` 
 ADD INDEX `IXFK_Car_Car Owner` (`car_owner_id` ASC)
;

ALTER TABLE `Car` 
 ADD INDEX `IXFK_Car_Office` (`office_id` ASC)
;

ALTER TABLE `Driver` 
 ADD INDEX `IXFK_Driver_Office` (`office_id` ASC)
;

ALTER TABLE `Office` 
 ADD INDEX `IXFK_Office_Manager` (`manager_id` ASC)
;

ALTER TABLE `Private Job` 
 ADD INDEX `IXFK_Private Job_Car` (`car_id` ASC)
;

ALTER TABLE `Private Job` 
 ADD INDEX `IXFK_Private Job_Driver` (`driver_id` ASC)
;

ALTER TABLE `Private Job` 
 ADD INDEX `IXFK_Private Job_Private Client` (`client_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Admin` 
 ADD CONSTRAINT `FK_Admin_Office`
	FOREIGN KEY (`office_id`) REFERENCES `Office` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Business Contract` 
 ADD CONSTRAINT `FK_Business Contract_Business Client`
	FOREIGN KEY (`client_id`) REFERENCES `Business Client` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Business Contract` 
 ADD CONSTRAINT `FK_Business Contract_Office`
	FOREIGN KEY (`office_id`) REFERENCES `Office` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Business Job` 
 ADD CONSTRAINT `FK_Business Job_Business Contract`
	FOREIGN KEY (`contract_id`) REFERENCES `Business Contract` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Business Job` 
 ADD CONSTRAINT `FK_Business Job_Car`
	FOREIGN KEY (`car_id`) REFERENCES `Car` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Business Job` 
 ADD CONSTRAINT `FK_Business Job_Driver`
	FOREIGN KEY (`driver_id`) REFERENCES `Driver` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Car` 
 ADD CONSTRAINT `FK_Car_Car Owner`
	FOREIGN KEY (`car_owner_id`) REFERENCES `Car Owner` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Car` 
 ADD CONSTRAINT `FK_Car_Office`
	FOREIGN KEY (`office_id`) REFERENCES `Office` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Driver` 
 ADD CONSTRAINT `FK_Driver_Office`
	FOREIGN KEY (`office_id`) REFERENCES `Office` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Office` 
 ADD CONSTRAINT `FK_Office_Manager`
	FOREIGN KEY (`manager_id`) REFERENCES `Manager` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Private Job` 
 ADD CONSTRAINT `FK_Private Job_Car`
	FOREIGN KEY (`car_id`) REFERENCES `Car` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Private Job` 
 ADD CONSTRAINT `FK_Private Job_Driver`
	FOREIGN KEY (`driver_id`) REFERENCES `Driver` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Private Job` 
 ADD CONSTRAINT `FK_Private Job_Private Client`
	FOREIGN KEY (`client_id`) REFERENCES `Private Client` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
